[build]
  command = "yarn run build"
  functions = "functions"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "yarn run dev:webpack"
  targetPort = 8079
  port = 8080
  publish = "dist"
  autoLaunch = false